# Generated by Django 5.2.1 on 2025-07-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('role', models.CharField(help_text='e.g. Backend Developer', max_length=100, verbose_name='Professional Role')),
                ('bio', models.TextField(verbose_name='Biography')),
                ('experience', models.PositiveIntegerField(default=1, verbose_name='Experience')),
                ('based_in', models.CharField(help_text='e.g. Remote / Germany', max_length=50, verbose_name='Based In')),
                ('availability', models.CharField(help_text='e.g. Freelance / Full-time', max_length=50, verbose_name='Availability')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profile Image')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV File')),
                ('project_count', models.PositiveIntegerField(default=0, verbose_name='Completed Projects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
