# Generated by Django 5.2.1 on 2025-07-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub')),
            ],
            options={
                'verbose_name': 'Site Info',
                'verbose_name_plural': 'Site Infos',
            },
        ),
    ]
