# Generated by Django 5.2.1 on 2025-07-01 10:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(blank=True, verbose_name='Short Description')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Full Description')),
                ('tech_stack', models.CharField(help_text='e.g. Django, React, PostgreSQL', max_length=255, verbose_name='Technologies Used')),
                ('project_type', models.CharField(help_text='e.g. Web App, API, Automation', max_length=100, verbose_name='Type')),
                ('main_image', models.ImageField(upload_to='projects/images/', verbose_name='Main Image')),
                ('source_code_url', models.URLField(blank=True, null=True, verbose_name='Source Code (GitHub)')),
                ('live_demo_url', models.URLField(blank=True, null=True, verbose_name='Live Demo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
