# Generated by Django 5.2.4 on 2025-07-17 17:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Short Description')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Full Description')),
                ('tech_stack', models.CharField(help_text='e.g. Django, React, PostgreSQL', max_length=255, verbose_name='Technologies Used')),
                ('project_type', models.CharField(help_text='e.g. Web App, API, Automation', max_length=100, verbose_name='Project Type')),
                ('main_image', models.ImageField(upload_to='projects/images/', verbose_name='Main Image')),
                ('source_code_url', models.URLField(blank=True, null=True, verbose_name='Source Code (GitHub)')),
                ('live_demo_url', models.URLField(blank=True, null=True, verbose_name='Live Demo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daterange', models.CharField(max_length=100, verbose_name='Date (e, g, 2020-2021)')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('institution', models.CharField(max_length=100, verbose_name='Institution / Position')),
                ('description', models.TextField(blank=True, verbose_name='Full Description')),
                ('column', models.CharField(choices=[('left', 'Left Column'), ('right', 'Right Column')], default='left', max_length=10, verbose_name='Display Column')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resume Entry',
                'verbose_name_plural': 'Resume Entries',
                'ordering': ['column', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CV_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('language', models.CharField(max_length=100, verbose_name='Language')),
                ('soft_skills', models.CharField(max_length=100, verbose_name='Soft-Skills')),
                ('hard_skills', models.CharField(max_length=100, verbose_name='Hard-Skills')),
                ('education', models.CharField(max_length=100, verbose_name='Education')),
                ('certification', models.CharField(max_length=100, verbose_name='Certification')),
                ('experience', models.CharField(max_length=100, verbose_name='Experience')),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ManyToManyField(to='resume.resume')),
            ],
            options={
                'verbose_name': 'CV PDF',
                'verbose_name_plural': 'CV PDFs',
                'ordering': ['first_name', '-created_at'],
            },
        ),
    ]
