# Generated by Django 5.2.4 on 2025-07-17 17:21

import ckeditor.fields
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Full Content')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/thumbnails/', verbose_name='Thumbnail Image')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='blog/main_images/', verbose_name='Main Article Image')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Author Name')),
                ('author_bio', models.TextField(blank=True, verbose_name='Author Bio')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Author Image')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Service Icon (For Card)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Main Image (For Details Page)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Feature Title')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Short Description')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='blog_app.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
            },
        ),
    ]
