# Generated by Django 5.2.4 on 2025-07-31 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogpost_content'),
        ('home', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='home.category'),
        ),
    ]
