# Generated by Django 5.2.1 on 2025-06-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_service_managers_service_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Service Icon (Image)'),
        ),
    ]
