# Generated by Django 5.2.1 on 2025-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_service_icon_service_icon_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Main Image (For Details Page)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Service Icon (For Card)'),
        ),
    ]
